# Generated by Django 5.0.2 on 2024-02-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='calculated_discount',
        ),
    ]
