# Generated by Django 5.0.2 on 2024-02-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_orderitem_calculated_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
