# Generated by Django 5.0.2 on 2024-02-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_orderitem_selected_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
