# Generated by Django 5.0.2 on 2024-02-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='success_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
