# Generated by Django 5.0.2 on 2024-02-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_order_success_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='success_uuid',
            new_name='order_uuid',
        ),
    ]
