# Generated by Django 5.0.2 on 2024-02-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_success_uuid_order_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fail_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
