# Generated by Django 5.0.2 on 2024-04-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_order_fail_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fail_uuid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_uuid',
        ),
    ]
