version: '3.9'

services:
  backend:
    build: .
    container_name: 'backend'
    command: poetry run python3 core/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

