version: '3.9'

services:
  backend:
    build: .
    container_name: 'backend'
    command: poetry run gunicorn core.wsgi --bind 0.0.0.0:8000
    # command: sleep infinity
    volumes:
      - ./core:/app
    networks:
      - postgres-network
    depends_on:
      - postgres
    environment:
      - is_production=true
      
  postgres:
    image: docker.arvancloud.ir/postgres:16.1-bullseye
    container_name: db
    environment:
      - POSTGRES_DB=admin_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-network
  
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - static_volume:/home/app/static_root
      # - media_volume:/home/app/media
    depends_on:
      - backend

volumes:
  postgres-volume:

networks:
  postgres-network: