version: '3.9'

services:
  backend:
    build: .
    container_name: 'backend'
    entrypoint: /entrypoint.sh
    # command: sleep infinity
    volumes:
      - ./core:/app
      - static_volume:/app/static_root/
      - media_volume:/app/media/
    networks:
      - postgres-network
    depends_on:
      - postgres
    environment:
      - is_production=true
      
  postgres:
    image: docker.arvancloud.ir/postgres:16.1-bullseye
    container_name: db
    env_file:
      - ./default.env
      - path: ./.database.env
        required: false
        
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-network
  
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static_root/
      - media_volume:/app/media/
    depends_on:
      - backend
    networks:
      - postgres-network

volumes:
  postgres-volume:
  static_volume:
  media_volume:

networks:
  postgres-network: