version: '3.9'

services:
  backend:
    build: .
    container_name: 'backend'
    entrypoint: /entrypoint.sh
    # command: sleep infinity
    networks:
      - postgres-network
    depends_on:
      - postgres
      
  postgres:
    image: docker.arvancloud.ir/postgres:16.1-bullseye
    container_name: db
    env_file:
      - ./default.env
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - postgres-network


networks:
  postgres-network: