version: '3.9'

services:
  backend:
    build: .
    container_name: 'backend'
    entrypoint: /entrypoint.sh
    # command: sleep infinity
    volumes:
      - ./core:/app
      - static_volume:/app/static_root/
      - media_volume:/app/media/
    networks:
      - postgres-network
    depends_on:
      - postgres
    environment:
      - is_production=true
      
  postgres:
    image: docker.arvancloud.ir/postgres:16.1-bullseye
    container_name: db
    env_file:
      - path: ./default.env
        required: true 
      - path: ./.database.env
        required: false
    command: ["postgres", "-c", "log_statement=all"]
        
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-network
  
  nginx:
    image: docker.arvancloud.ir/nginx:1.25.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
      - static_volume:/app/static_root/
      - media_volume:/app/media/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    depends_on:
      - backend
    networks:
      - postgres-network
      
  certbot:
    image: docker.arvancloud.ir/certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email h410mi3@gmail.com -d babolsarbyte.ir --agree-tos

volumes:
  postgres-volume:
  static_volume:
  media_volume:

networks:
  postgres-network: