# Generated by Django 5.0.1 on 2024-01-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='pannel_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='port',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.IntegerField(null=True),
        ),
    ]
