# Generated by Django 5.0.1 on 2024-02-01 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvsize',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.discountcode'),
        ),
    ]
