# Generated by Django 5.0.1 on 2024-02-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
