# Generated by Django 5.0.2 on 2024-02-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_id'),
    ]

    operations = [
        migrations.RunSQL("SELECT setval('product_product_id_seq', 1000)",migrations.RunSQL.noop)
    ]
