# Generated by Django 5.0.2 on 2024-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_tvsize_discount_delete_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvsize',
            name='size',
            field=models.CharField(max_length=25, verbose_name='سایز'),
        ),
    ]
