# Generated by Django 5.0.1 on 2024-02-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_footer_navbar_sitesettings_slider_subfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfooter',
            name='link',
            field=models.CharField(default='#', max_length=250),
        ),
    ]
