name: CD for shop
on:
    pull_request:
      branches:
        - production
  
jobs:
    quality-assurance:
      name: check CI before deploy 
      uses: ./.github/workflows/ci.yml

    simple_CD:
      name: Django CD
      needs:
        - quality-assurance
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Connect and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.USER}}
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{secrets.HOST}}
          script: |
            cd modern_shop
            docker compose -f docker-compose-prod.yaml down
            git pull
            docker compose -f docker-compose-prod.yaml build
            docker compose -f docker-compose-prod.yaml up -d --force-recreate
