name: CI for shop
on: 
  push:
    branches:
      - general
      - account
      - product
      - feature
      - cart
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  quality-assurance:
      name: Django CI
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: update docker compose
            run: sudo apt-get install docker-compose-plugin
          - name: Check Docker Compose Version
            run: docker-compose --version
          - name: up the container
            run: docker-compose -f docker-compose-prod.yaml up -d
          - name: run tests
            run:  docker exec backend bash -c "poetry run python3 manage.py test --no-input"