name: CI for shop
on: ['push']

jobs:
    simple_build:
      name: Django CI
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Install docker
            run: sudo snap install docker
          - name: up the container
            run: docker-compose -f docker-compose-dev.yaml up
          - name: run tests
            run: docker exec -it backend bash -c "poetry run python3 core/manage.py test"

