name: CI for shop
on: ['push']

jobs:
    simple_build:
      name: Django CI
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Install docker
            run: sudo snap install docker
          # - name: Login to Docker Hub
          #   uses: docker/login-action@v3
            # with:
            #   username: erfankarimi
            #   password: 1234docker123
          # - name: Set up Docker Buildx
          #   uses: docker/setup-buildx-action@v3
          - name: up the container
            run: docker-compose -f docker-compose-dev.yaml up -d
          - name: run tests
            run: docker exec backend bash -c "poetry run python3 core/manage.py test"

